# ==============================================================================
# AutoSync - Configuration Example
# Save this file as: ~/.config/autosync/config.toml
# ==============================================================================

# ------------------------------------------------------------------------------
# PATH RULES:
# - Starts with "~" : Relative to your home folder (e.g., ~/Documents).
# - Starts with "/" : Absolute local path. (Warning: Ensure your user has read/write permissions for this path).
# - Starts with a word: Rclone Remote. (You must configure your remotes in rclone first, e.g., GDrive:).
# ------------------------------------------------------------------------------
[[pairs]]
path1 = "~/Pictures/Wallpapers"
path2 = "googledrive:Wallpapers"
log = "~/Logs/Wallpapers"

[[pairs]]
path1 = "~/keepassxc"
path2 = "googledrive:keepassxc"
log = "~/Logs/keepassxc"

[[pairs]]
path1 = "~/Documents"
path2 = "googledrive:Documents"
log = "~/Logs/Documents"
