[General]
AlwaysEnablePreviewZoom=false
FileParameterDefaultPath=/home/tymcftw
FolderParameterDefaultValue=/home/tymcftw
LogosAreVisible=true
OutputMessageMode=0
PreviewTimeout=16
SelectedFilter=2dc05ce11791d256040f0c746ed03ff7

[Config]
ExpandedFolders=<b>Layers</b>
FilterSources=${GMIC_PATH}/.gmic, ${HOME}/.gmic
FilterTranslation=false
HighDPIEnabled=false
LanguageCode=
MainWindowMaximized=true
MainWindowPosition=@Point(0 0)
MainWindowRect=@Rect(0 0 1920 1016)
NativeColorDialogs=false
NativeFileDialogs=false
NotifyIfStartupUpdateFails=true
OfficialFilterSource=EnabledWithUpdates
PanelSize0=378
PanelSize1=756
PanelSize2=756
ParamsVerticalSplitterSizeBottom=0
ParamsVerticalSplitterSizeTop=948
PreviewEnabled=true
PreviewPosition=Right
PreviewSplitterType=2
RefreshInternetUpdate=true
ScreenGeometries="(0,0,1920,1080)"
UpdatesPeriodicityValue=720

[LastExecution]
ExitedNormally=true
HostApplicationID=3015
gmic_version=403
host_standalone\Arguments=
host_standalone\Command=
host_standalone\FilterHash=
host_standalone\FilterPath=
host_standalone\GmicStatusString=
host_standalone\InputMode=0
host_standalone\OutputMode=0

[Standalone]
SaveAsSelectedFilter=PNG file (*.PNG *.png)
