complete -c garage -n "__fish_use_subcommand" -s h -l rpc-host -d 'Host to connect to for admin operations, in the format: `<full-node-id>@<ip>:<port>`'
complete -c garage -n "__fish_use_subcommand" -l allow-world-readable-secrets -d 'Skip permission check on files containing secrets'
complete -c garage -n "__fish_use_subcommand" -s s -l rpc-secret -d 'RPC secret network key, used to replace `rpc_secret` in config.toml when running the daemon or doing admin operations'
complete -c garage -n "__fish_use_subcommand" -l rpc-secret-file -d 'RPC secret network key, used to replace `rpc_secret` in config.toml and rpc-secret when running the daemon or doing admin operations'
complete -c garage -n "__fish_use_subcommand" -l admin-token -d 'Admin API authentication token, replaces `admin.admin_token` in config.toml when running the Garage daemon'
complete -c garage -n "__fish_use_subcommand" -l admin-token-file -d 'Admin API authentication token file path, replaces `admin.admin_token` in config.toml and admin-token when running the Garage daemon'
complete -c garage -n "__fish_use_subcommand" -l metrics-token -d 'Metrics API authentication token, replaces `admin.metrics_token` in config.toml when running the Garage daemon'
complete -c garage -n "__fish_use_subcommand" -l metrics-token-file -d 'Metrics API authentication token file path, replaces `admin.metrics_token` in config.toml and metrics-token when running the Garage daemon'
complete -c garage -n "__fish_use_subcommand" -s c -l config -d 'Path to configuration file'
complete -c garage -n "__fish_use_subcommand" -l help -d 'Prints help information'
complete -c garage -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_use_subcommand" -f -a "server" -d 'Run Garage server'
complete -c garage -n "__fish_use_subcommand" -f -a "status" -d 'Get network status'
complete -c garage -n "__fish_use_subcommand" -f -a "node" -d 'Operations on individual Garage nodes'
complete -c garage -n "__fish_use_subcommand" -f -a "layout" -d 'Operations on the assignment of node roles in the cluster layout'
complete -c garage -n "__fish_use_subcommand" -f -a "bucket" -d 'Operations on buckets'
complete -c garage -n "__fish_use_subcommand" -f -a "key" -d 'Operations on S3 access keys'
complete -c garage -n "__fish_use_subcommand" -f -a "admin-token" -d 'Operations on admin API tokens'
complete -c garage -n "__fish_use_subcommand" -f -a "repair" -d 'Start repair of node data on remote node'
complete -c garage -n "__fish_use_subcommand" -f -a "offline-repair" -d 'Offline reparation of node data (these repairs must be run offline directly on the server node)'
complete -c garage -n "__fish_use_subcommand" -f -a "stats" -d 'Gather node statistics'
complete -c garage -n "__fish_use_subcommand" -f -a "worker" -d 'Manage background workers'
complete -c garage -n "__fish_use_subcommand" -f -a "block" -d 'Low-level node-local debug operations on data blocks'
complete -c garage -n "__fish_use_subcommand" -f -a "meta" -d 'Operations on the metadata db'
complete -c garage -n "__fish_use_subcommand" -f -a "convert-db" -d 'Convert metadata db between database engine formats'
complete -c garage -n "__fish_use_subcommand" -f -a "admin-api-schema" -d 'Output openapi JSON schema for admin api'
complete -c garage -n "__fish_use_subcommand" -f -a "json-api" -d 'Directly invoke the admin API using a JSON payload. The result is printed to `stdout` in JSON format'
complete -c garage -n "__fish_use_subcommand" -f -a "completions" -d 'Generate completions for a shell'
complete -c garage -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c garage -n "__fish_seen_subcommand_from server" -l single-node -d 'Automatically configure a single-node layout in the cluster. Garage will refuse to run if the cluster already has other nodes'
complete -c garage -n "__fish_seen_subcommand_from server" -l default-access-key -d 'Configure a default S3 API key using environment variables `GARAGE_DEFAULT_ACCESS_KEY` and `GARAGE_DEFAULT_SECRET_KEY`. Requires `--single-node`'
complete -c garage -n "__fish_seen_subcommand_from server" -l default-bucket -d 'Configure a default bucket using environment variable `GARAGE_DEFAULT_BUCKET`. Implies `--default-access-key`. Requires `--single-node`'
complete -c garage -n "__fish_seen_subcommand_from server" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from server" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from status" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from status" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from node" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from node" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from node" -f -a "id" -d 'Print the full node ID (public key) of this Garage node, and its publicly reachable IP address and port if they are specified in configfile under `rpc_public_addr`'
complete -c garage -n "__fish_seen_subcommand_from node" -f -a "connect" -d 'Connect to Garage node that is currently isolated from the system'
complete -c garage -n "__fish_seen_subcommand_from node" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c garage -n "__fish_seen_subcommand_from id" -s q -l quiet -d 'Do not print usage instructions to stderr'
complete -c garage -n "__fish_seen_subcommand_from id" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from id" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from connect" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from connect" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from layout" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from layout" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from layout" -f -a "assign" -d 'Assign role to Garage node'
complete -c garage -n "__fish_seen_subcommand_from layout" -f -a "remove" -d 'Remove role from Garage cluster node'
complete -c garage -n "__fish_seen_subcommand_from layout" -f -a "config" -d 'Configure parameters value for the layout computation'
complete -c garage -n "__fish_seen_subcommand_from layout" -f -a "show" -d 'Show roles currently assigned to nodes and changes staged for commit'
complete -c garage -n "__fish_seen_subcommand_from layout" -f -a "apply" -d 'Apply staged changes to cluster layout'
complete -c garage -n "__fish_seen_subcommand_from layout" -f -a "revert" -d 'Revert staged changes to cluster layout'
complete -c garage -n "__fish_seen_subcommand_from layout" -f -a "history" -d 'View the history of layouts in the cluster'
complete -c garage -n "__fish_seen_subcommand_from layout" -f -a "skip-dead-nodes" -d 'Skip dead nodes when awaiting for a new layout version to be synchronized'
complete -c garage -n "__fish_seen_subcommand_from layout" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c garage -n "__fish_seen_subcommand_from assign" -s z -l zone -d 'Location (zone or datacenter) of the node'
complete -c garage -n "__fish_seen_subcommand_from assign" -s c -l capacity -d 'Storage capacity, in bytes (supported suffixes: B, KB, MB, GB, TB, PB)'
complete -c garage -n "__fish_seen_subcommand_from assign" -s t -l tag -d 'Optional tags to add to node'
complete -c garage -n "__fish_seen_subcommand_from assign" -l replace -d 'Replaced node(s): list of node IDs that will be removed from the current cluster'
complete -c garage -n "__fish_seen_subcommand_from assign" -s g -l gateway -d 'Gateway-only node'
complete -c garage -n "__fish_seen_subcommand_from assign" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from assign" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from remove" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from remove" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from config" -s r -l redundancy -d 'Zone redundancy parameter (\'none\'/\'max\' or integer)'
complete -c garage -n "__fish_seen_subcommand_from config" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from config" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from show" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from show" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from apply" -l version -d 'Version number of new configuration: this command will fail if it is not exactly 1 + the previous configuration\'s version'
complete -c garage -n "__fish_seen_subcommand_from apply" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from revert" -l yes -d 'The revert operation will not be ran unless this flag is added'
complete -c garage -n "__fish_seen_subcommand_from revert" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from revert" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from history" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from history" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from skip-dead-nodes" -l version -d 'Version number of the layout to assume is currently up-to-date. This will generally be the current layout version'
complete -c garage -n "__fish_seen_subcommand_from skip-dead-nodes" -l allow-missing-data -d 'Allow the skip even if a quorum of nodes could not be found for the data among the remaining nodes'
complete -c garage -n "__fish_seen_subcommand_from skip-dead-nodes" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from bucket" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from bucket" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from bucket" -f -a "list" -d 'List buckets'
complete -c garage -n "__fish_seen_subcommand_from bucket" -f -a "info" -d 'Get bucket info'
complete -c garage -n "__fish_seen_subcommand_from bucket" -f -a "create" -d 'Create bucket'
complete -c garage -n "__fish_seen_subcommand_from bucket" -f -a "delete" -d 'Delete bucket'
complete -c garage -n "__fish_seen_subcommand_from bucket" -f -a "alias" -d 'Alias bucket under new name'
complete -c garage -n "__fish_seen_subcommand_from bucket" -f -a "unalias" -d 'Remove bucket alias'
complete -c garage -n "__fish_seen_subcommand_from bucket" -f -a "allow" -d 'Allow key to read or write to bucket'
complete -c garage -n "__fish_seen_subcommand_from bucket" -f -a "deny" -d 'Deny key from reading or writing to bucket'
complete -c garage -n "__fish_seen_subcommand_from bucket" -f -a "website" -d 'Expose as website or not'
complete -c garage -n "__fish_seen_subcommand_from bucket" -f -a "set-quotas" -d 'Set the quotas for this bucket'
complete -c garage -n "__fish_seen_subcommand_from bucket" -f -a "cleanup-incomplete-uploads" -d 'Clean up (abort) old incomplete multipart uploads'
complete -c garage -n "__fish_seen_subcommand_from bucket" -f -a "inspect-object" -d 'Inspect an object in a bucket'
complete -c garage -n "__fish_seen_subcommand_from bucket" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c garage -n "__fish_seen_subcommand_from list" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from list" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from info" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from info" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from create" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from create" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from delete" -l yes -d 'If this flag is not given, the bucket won\'t be deleted'
complete -c garage -n "__fish_seen_subcommand_from delete" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from delete" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from alias" -l local -d 'Make this alias local to the specified access key'
complete -c garage -n "__fish_seen_subcommand_from alias" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from alias" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from unalias" -l local -d 'Unalias in bucket namespace local to this access key'
complete -c garage -n "__fish_seen_subcommand_from unalias" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from unalias" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from allow" -l key -d 'Access key name or ID'
complete -c garage -n "__fish_seen_subcommand_from allow" -l read -d 'Allow/deny read operations'
complete -c garage -n "__fish_seen_subcommand_from allow" -l write -d 'Allow/deny write operations'
complete -c garage -n "__fish_seen_subcommand_from allow" -l owner -d 'Allow/deny administrative operations operations (such as deleting bucket or changing bucket website configuration)'
complete -c garage -n "__fish_seen_subcommand_from allow" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from allow" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from deny" -l key -d 'Access key name or ID'
complete -c garage -n "__fish_seen_subcommand_from deny" -l read -d 'Allow/deny read operations'
complete -c garage -n "__fish_seen_subcommand_from deny" -l write -d 'Allow/deny write operations'
complete -c garage -n "__fish_seen_subcommand_from deny" -l owner -d 'Allow/deny administrative operations operations (such as deleting bucket or changing bucket website configuration)'
complete -c garage -n "__fish_seen_subcommand_from deny" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from deny" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from website" -s i -l index-document -d 'Index document: the suffix appended to request paths ending by /'
complete -c garage -n "__fish_seen_subcommand_from website" -s e -l error-document -d 'Error document: the optional document returned when an error occurs'
complete -c garage -n "__fish_seen_subcommand_from website" -l allow -d 'Create'
complete -c garage -n "__fish_seen_subcommand_from website" -l deny -d 'Delete'
complete -c garage -n "__fish_seen_subcommand_from website" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from website" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from set-quotas" -l max-size -d 'Set a maximum size for the bucket (specify a size e.g. in MiB or GiB, or `none` for no size restriction)'
complete -c garage -n "__fish_seen_subcommand_from set-quotas" -l max-objects -d 'Set a maximum number of objects for the bucket (or `none` for no restriction)'
complete -c garage -n "__fish_seen_subcommand_from set-quotas" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from set-quotas" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from cleanup-incomplete-uploads" -l older-than -d 'Abort multipart uploads older than this value'
complete -c garage -n "__fish_seen_subcommand_from cleanup-incomplete-uploads" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from cleanup-incomplete-uploads" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from inspect-object" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from inspect-object" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from key" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from key" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from key" -f -a "list" -d 'List keys'
complete -c garage -n "__fish_seen_subcommand_from key" -f -a "info" -d 'Get key info'
complete -c garage -n "__fish_seen_subcommand_from key" -f -a "create" -d 'Create new key'
complete -c garage -n "__fish_seen_subcommand_from key" -f -a "rename" -d 'Rename key'
complete -c garage -n "__fish_seen_subcommand_from key" -f -a "delete" -d 'Delete key'
complete -c garage -n "__fish_seen_subcommand_from key" -f -a "allow" -d 'Set permission flags for key'
complete -c garage -n "__fish_seen_subcommand_from key" -f -a "deny" -d 'Unset permission flags for key'
complete -c garage -n "__fish_seen_subcommand_from key" -f -a "import" -d 'Import key'
complete -c garage -n "__fish_seen_subcommand_from key" -f -a "set" -d 'Set parameters for an access key'
complete -c garage -n "__fish_seen_subcommand_from key" -f -a "delete-expired" -d 'Delete all expired access keys'
complete -c garage -n "__fish_seen_subcommand_from key" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c garage -n "__fish_seen_subcommand_from list" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from list" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from info" -l show-secret -d 'Whether to display the secret key'
complete -c garage -n "__fish_seen_subcommand_from info" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from info" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from create" -l expires-in -d 'Set an expiration time for the access key (see `docs.rs/parse_duration` for date format)'
complete -c garage -n "__fish_seen_subcommand_from create" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from create" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from rename" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from rename" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from delete" -l yes -d 'Confirm deletion'
complete -c garage -n "__fish_seen_subcommand_from delete" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from delete" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from allow" -l create-bucket -d 'Flag that allows key to create buckets using S3\'s `CreateBucket` call'
complete -c garage -n "__fish_seen_subcommand_from allow" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from allow" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from deny" -l create-bucket -d 'Flag that allows key to create buckets using S3\'s `CreateBucket` call'
complete -c garage -n "__fish_seen_subcommand_from deny" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from deny" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from import" -s n -d 'Key name'
complete -c garage -n "__fish_seen_subcommand_from import" -l yes -d 'Confirm key import'
complete -c garage -n "__fish_seen_subcommand_from import" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from import" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from set" -l expires-in -d 'Set an expiration time for the access key (see `docs.rs/parse_duration` for date format)'
complete -c garage -n "__fish_seen_subcommand_from set" -l never-expires -d 'Set the access key to never expire'
complete -c garage -n "__fish_seen_subcommand_from set" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from set" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from delete-expired" -l yes -d 'Confirm deletion'
complete -c garage -n "__fish_seen_subcommand_from delete-expired" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from delete-expired" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from admin-token" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from admin-token" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from admin-token" -f -a "list" -d 'List all admin API tokens'
complete -c garage -n "__fish_seen_subcommand_from admin-token" -f -a "info" -d 'Fetch info about a specific admin API token'
complete -c garage -n "__fish_seen_subcommand_from admin-token" -f -a "create" -d 'Create new admin API token'
complete -c garage -n "__fish_seen_subcommand_from admin-token" -f -a "rename" -d 'Rename an admin API token'
complete -c garage -n "__fish_seen_subcommand_from admin-token" -f -a "set" -d 'Set parameters for an admin API token'
complete -c garage -n "__fish_seen_subcommand_from admin-token" -f -a "delete" -d 'Delete an admin API token'
complete -c garage -n "__fish_seen_subcommand_from admin-token" -f -a "delete-expired" -d 'Delete all expired admin API tokens'
complete -c garage -n "__fish_seen_subcommand_from admin-token" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c garage -n "__fish_seen_subcommand_from list" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from list" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from info" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from info" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from create" -l expires-in -d 'Set an expiration time for the token (see `docs.rs/parse_duration` for date format)'
complete -c garage -n "__fish_seen_subcommand_from create" -l scope -d 'Set a limited scope for the token, as a comma-separated list of admin API functions (e.g. `GetClusterStatus`, etc.). The default scope is `*`, which allows access to all admin API functions. Note that granting a scope that allows `CreateAdminToken` or `UpdateAdminToken` allows for privilege escalation, and is therefore equivalent to `*`'
complete -c garage -n "__fish_seen_subcommand_from create" -s q -l quiet -d 'Print only the newly generated API token to stdout'
complete -c garage -n "__fish_seen_subcommand_from create" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from create" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from rename" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from rename" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from set" -l expires-in -d 'Set an expiration time for the token (see `docs.rs/parse_duration` for date format)'
complete -c garage -n "__fish_seen_subcommand_from set" -l scope -d 'Set a limited scope for the token, as a comma-separated list of admin API functions (e.g. `GetClusterStatus`, etc.), or `*` to allow all admin API functions. Use `--scope=+Scope1,Scope2` to add scopes to the existing list, and `--scope=-Scope1,Scope2` to remove scopes from the existing list. Note that granting a scope that allows `CreateAdminToken` or `UpdateAdminToken` allows for privilege escalation, and is therefore equivalent to `*`'
complete -c garage -n "__fish_seen_subcommand_from set" -l never-expires -d 'Set the token to never expire'
complete -c garage -n "__fish_seen_subcommand_from set" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from set" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from delete" -l yes -d 'Confirm deletion'
complete -c garage -n "__fish_seen_subcommand_from delete" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from delete" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from delete-expired" -l yes -d 'Confirm deletion'
complete -c garage -n "__fish_seen_subcommand_from delete-expired" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from delete-expired" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from repair" -s a -l all-nodes -d 'Launch repair operation on all nodes'
complete -c garage -n "__fish_seen_subcommand_from repair" -l yes -d 'Confirm the launch of the repair operation'
complete -c garage -n "__fish_seen_subcommand_from repair" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from repair" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from repair" -f -a "tables" -d 'Do a full sync of metadata tables'
complete -c garage -n "__fish_seen_subcommand_from repair" -f -a "blocks" -d 'Repair (resync/rebalance) the set of stored blocks in the cluster'
complete -c garage -n "__fish_seen_subcommand_from repair" -f -a "clear-resync-queue" -d 'Clear the block resync queue. The list of blocks in errored state is cleared as well. You MUST run `garage repair blocks` after invoking this'
complete -c garage -n "__fish_seen_subcommand_from repair" -f -a "versions" -d 'Repropagate object deletions to the version table'
complete -c garage -n "__fish_seen_subcommand_from repair" -f -a "mpu" -d 'Repropagate object deletions to the multipart upload table'
complete -c garage -n "__fish_seen_subcommand_from repair" -f -a "block-refs" -d 'Repropagate version deletions to the block ref table'
complete -c garage -n "__fish_seen_subcommand_from repair" -f -a "block-rc" -d 'Recalculate block reference counters'
complete -c garage -n "__fish_seen_subcommand_from repair" -f -a "aliases" -d 'Fix inconsistency in bucket aliases (WARNING: EXPERIMENTAL)'
complete -c garage -n "__fish_seen_subcommand_from repair" -f -a "scrub" -d 'Verify integrity of all blocks on disc'
complete -c garage -n "__fish_seen_subcommand_from repair" -f -a "rebalance" -d 'Rebalance data blocks among HDDs on individual nodes'
complete -c garage -n "__fish_seen_subcommand_from repair" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c garage -n "__fish_seen_subcommand_from tables" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from tables" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from blocks" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from blocks" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from clear-resync-queue" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from clear-resync-queue" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from versions" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from versions" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from mpu" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from mpu" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from block-refs" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from block-refs" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from block-rc" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from block-rc" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from aliases" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from aliases" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from scrub" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from scrub" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from scrub" -f -a "start" -d 'Start scrub'
complete -c garage -n "__fish_seen_subcommand_from scrub" -f -a "pause" -d 'Pause scrub (it will resume automatically after 24 hours)'
complete -c garage -n "__fish_seen_subcommand_from scrub" -f -a "resume" -d 'Resume paused scrub'
complete -c garage -n "__fish_seen_subcommand_from scrub" -f -a "cancel" -d 'Cancel scrub in progress'
complete -c garage -n "__fish_seen_subcommand_from scrub" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c garage -n "__fish_seen_subcommand_from start" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from start" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from pause" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from pause" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from resume" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from resume" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from cancel" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from cancel" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from rebalance" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from rebalance" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from offline-repair" -l yes -d 'Confirm the launch of the repair operation'
complete -c garage -n "__fish_seen_subcommand_from offline-repair" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from offline-repair" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from offline-repair" -f -a "k2v_item_counters" -d 'Repair K2V item counters'
complete -c garage -n "__fish_seen_subcommand_from offline-repair" -f -a "object_counters" -d 'Repair object counters'
complete -c garage -n "__fish_seen_subcommand_from offline-repair" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c garage -n "__fish_seen_subcommand_from k2v_item_counters" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from k2v_item_counters" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from object_counters" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from object_counters" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from stats" -s a -l all-nodes -d 'Gather statistics from all nodes'
complete -c garage -n "__fish_seen_subcommand_from stats" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from stats" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from worker" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from worker" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from worker" -f -a "list" -d 'List all workers on Garage node'
complete -c garage -n "__fish_seen_subcommand_from worker" -f -a "info" -d 'Get detailed information about a worker'
complete -c garage -n "__fish_seen_subcommand_from worker" -f -a "get" -d 'Get worker parameter'
complete -c garage -n "__fish_seen_subcommand_from worker" -f -a "set" -d 'Set worker parameter'
complete -c garage -n "__fish_seen_subcommand_from worker" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c garage -n "__fish_seen_subcommand_from list" -s b -l busy -d 'Show only busy workers'
complete -c garage -n "__fish_seen_subcommand_from list" -s e -l errors -d 'Show only workers with errors'
complete -c garage -n "__fish_seen_subcommand_from list" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from list" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from info" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from info" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from get" -s a -l all-nodes -d 'Gather variable values from all nodes'
complete -c garage -n "__fish_seen_subcommand_from get" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from get" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from set" -s a -l all-nodes -d 'Set variable values on all nodes'
complete -c garage -n "__fish_seen_subcommand_from set" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from set" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from block" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from block" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from block" -f -a "list-errors" -d 'List all blocks that currently have a resync error'
complete -c garage -n "__fish_seen_subcommand_from block" -f -a "info" -d 'Get detailed information about a single block'
complete -c garage -n "__fish_seen_subcommand_from block" -f -a "retry-now" -d 'Retry now the resync of one or many blocks'
complete -c garage -n "__fish_seen_subcommand_from block" -f -a "purge" -d 'Delete all objects referencing a missing block'
complete -c garage -n "__fish_seen_subcommand_from block" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c garage -n "__fish_seen_subcommand_from list-errors" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from list-errors" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from info" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from info" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from retry-now" -l all -d 'Retry all blocks that have a resync error'
complete -c garage -n "__fish_seen_subcommand_from retry-now" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from retry-now" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from purge" -l yes -d 'Mandatory to confirm this operation'
complete -c garage -n "__fish_seen_subcommand_from purge" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from purge" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from meta" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from meta" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from meta" -f -a "snapshot" -d 'Save a snapshot of the metadata db file'
complete -c garage -n "__fish_seen_subcommand_from meta" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c garage -n "__fish_seen_subcommand_from snapshot" -l all -d 'Run on all nodes instead of only local node'
complete -c garage -n "__fish_seen_subcommand_from snapshot" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from snapshot" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from convert-db" -s i -d 'Input database path (not the same as `metadata_dir`, see <https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/#db_engine>'
complete -c garage -n "__fish_seen_subcommand_from convert-db" -s a -d 'Input database engine (lmdb or sqlite; limited by db engines enabled in this build)'
complete -c garage -n "__fish_seen_subcommand_from convert-db" -s o -d 'Output database path'
complete -c garage -n "__fish_seen_subcommand_from convert-db" -s b -d 'Output database engine'
complete -c garage -n "__fish_seen_subcommand_from convert-db" -l lmdb-map-size -d 'LMDB map size override (supported suffixes: B, KiB, MiB, GiB, TiB, PiB)'
complete -c garage -n "__fish_seen_subcommand_from convert-db" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from convert-db" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from admin-api-schema" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from admin-api-schema" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from json-api" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from json-api" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from completions" -s V -l version -d 'Prints version information'
complete -c garage -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c garage -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
