[General]
__APP_VERSION__=0.5.0
airplayFps=30
airplayNoHold=true
airplayUseLegacyPorts=true
autoCheckUpdates=true
autoConnectWirelessDevices=true
autoEnableWifiConnections=true
autoRaiseWindow=true
connectionTimeout=30
defaultJailbrokenRootPassword=097281
devdiskimgpath=/home/tymcftw/.idescriptor/devdiskimages
iconSizeBaseMultiplier=1
showV4L2=true
switchToNewDevice=true
theme=System Default
unmountiFuseOnExit=false
useUnsecureBackend-ipatool=true
wirelessFileServerPort=8080

[seenDevices]
00008101-000930E42E9A001E=true
