[Audio]
PreferredLanguage=eng
Volume=100

[General]
FileDialogLastLocation=file:///home/tymcftw/Desktop
LastPlayedFile=file:///home/tymcftw/Downloads/Gymkata (1985) (DVD).mkv

[Playlist]
Visible=true
