[Audio]
PreferredLanguage=eng
Volume=100

[General]
FileDialogLastLocation=file:///home/tymcftw/Desktop
LastPlayedFile=file:///home/tymcftw/Downloads/The Last Duel (2021)/The.Last.Duel.2021.1080p.WEBRip.x264.AAC5.1-%5BYTS.MX%5D.mp4
