[Audio]
PreferredLanguage=eng
Volume=100

[General]
FileDialogLastLocation=file:///home/tymcftw/Desktop
LastPlayedFile=file:///home/tymcftw/Downloads/Donnie Brasco 1997 Extended Cut 1080p BluRay HEVC x265 5.1 BONE.mkv
