[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\r/home/tymcftw)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\x94\0\0\x1@\0\0\x5\xe8\0\0\x3\x85\0\0\x2\x94\0\0\x1\\\0\0\x5\xe8\0\0\x3\x85\0\0\0\0\0\0\0\0\a\x80\0\0\x2\x94\0\0\x1\\\0\0\x5\xe8\0\0\x3\x85)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(853 480)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///mnt/SD1/dropbox/backups/digestive.swf, file:///mnt/SD1/dropbox/backups/OrgansAsPartOfBodySystem.swf, file:///home/tymcftw/Downloads/POV_Threesomes_With_MILFs_And_Younger_Lovers_1080p.mp4, file:///home/tymcftw/Desktop/2011-06-10%20summer%20time%20%2711/summer%20time%20%2711%20022.MOD, file:///tmp/ark-ihCEvU/2011-06-10%20summer%20time%20%2711/summer%20time%20%2711%20005.MOD, file:///home/tymcftw/Desktop/Voice_Memo_-_2019-10-19_14_41_25_-_708_Admiralty_Way.m4a, file:///run/user/1000/kio-fuse-bdcEdh/afc/00008101-000930e42e9a001e/Music/Cache/a5d721d6-9d6d-4d10-b628-c3659a215c95.m4a, file:///run/user/1000/kio-fuse-bdcEdh/afc/00008101-000930e42e9a001e/Music/Cache/8c107644-dbc3-4611-813a-f6c1b7a9633e.m4a, file:///home/tymcftw/Documents/Jenn%27s%20iPhone%207%20Plus/Jenn%27s%20iPhone%207%20Plus/AccessibleFiles/Purchases/import_FD87A3B6-FF6C-47F6-9944-D4513A5A8E62.m4a, file:///home/tymcftw/Desktop/537.amr, file:///home/tymcftw/Documents/Devices/jenniphone7/jenniphone7/Jenn%27s%20iPhone/HomeDomain/Library/Voicemail/537.amr, file:///home/tymcftw/Documents/Devices/jenniphone7/jenniphone7/Jenn%27s%20iPhone/HomeDomain/Library/Voicemail/Greeting.amr, file:///home/tymcftw/Documents/jenniphone7/jenniphone7/backup/Jenn%27s%20iPhone/Messages/2020-06-29%2018%2039%2039%20-%20Chloe%20Mclain/2019-08-16%2017%2033%2045%20-%20Chloe%20Mclain%20-%20Audio%20Message.caf, file:///home/tymcftw/Desktop/2019-08-16%2017%2033%2045%20-%20Chloe%20Mclain%20-%20Audio%20Message.caf
times=0, 0, 0, 9010, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
